"use client";

import React, { useState, useEffect } from "react";
import { Sliders, AlertTriangle, ShieldCheck, Download, Trash2 } from "lucide-react";
import AudioUploader from "@/components/AudioUploader";
import PitchControls from "@/components/PitchControls";
import AudioPlayer from "@/components/AudioPlayer";
import ProcessingStatus from "@/components/ProcessingStatus";
import { useAudioPlayer } from "@/hooks/useAudioPlayer";
import { processPitchShift } from "@/lib/ffmpeg";

export default function Home() {
  // File states
  const [file, setFile] = useState<File | null>(null);
  const [duration, setDuration] = useState<number | null>(null);
  const [originalUrl, setOriginalUrl] = useState<string | null>(null);

  // Pitch adjustment state (in semitones)
  const [pitchSemitones, setPitchSemitones] = useState<number>(0);

  // FFmpeg and progress states
  const [isProcessing, setIsProcessing] = useState<boolean>(false);
  const [progress, setProgress] = useState<number>(0);
  const [statusMessage, setStatusMessage] = useState<string>("");
  const [error, setError] = useState<string | null>(null);

  // Revoke object URL on unmount or file reset
  useEffect(() => {
    if (file) {
      const url = URL.createObjectURL(file);
      const timeoutId = setTimeout(() => {
        setOriginalUrl(url);
      }, 0);
      return () => {
        clearTimeout(timeoutId);
        URL.revokeObjectURL(url);
      };
    } else {
      const timeoutId = setTimeout(() => {
        setOriginalUrl(null);
      }, 0);
      return () => clearTimeout(timeoutId);
    }
  }, [file]);

  // Main real-time player connected to live pitch shifter
  const player = useAudioPlayer({ url: originalUrl, pitch: pitchSemitones });

  const handleFileSelect = (selectedFile: File, fileDuration: number) => {
    setFile(selectedFile);
    setDuration(fileDuration);
    setError(null);
    setPitchSemitones(0);
  };

  const handleReset = () => {
    player.pause();
    setFile(null);
    setDuration(null);
    setPitchSemitones(0);
    setError(null);
  };

  // Helper to run FFmpeg offline export
  const exportAudio = async (format: "mp3" | "wav") => {
    if (!file) return;

    // Pause live playback to save CPU during encoding
    player.pause();

    setIsProcessing(true);
    setProgress(0);
    setStatusMessage("Initializing FFmpeg...");
    setError(null);

    try {
      const result = await processPitchShift({
        file,
        semitones: pitchSemitones,
        outputFormat: format,
        onProgress: (p) => setProgress(p),
        onLog: (msg) => setStatusMessage(msg),
      });

      // Trigger standard browser download
      const baseName = file.name.replace(/\.[^/.]+$/, "");
      const semitoneStr = pitchSemitones === 0 ? "0" : `${pitchSemitones > 0 ? "+" : ""}${pitchSemitones}`;
      const filename = `${baseName}_shifted_${semitoneStr}_semitones.${format}`;

      const a = document.createElement("a");
      a.href = result.url;
      a.download = filename;
      a.click();

      // Revoke the temporary url generated by FFmpeg
      setTimeout(() => {
        URL.revokeObjectURL(result.url);
      }, 2000);
      
    } catch (err: unknown) {
      console.error(err);
      const errorMessage = err instanceof Error ? err.message : String(err);
      setError(
        errorMessage ||
          "An error occurred while rendering the output file. The browser might have run out of memory."
      );
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <main className="flex-1 w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12 flex flex-col min-h-screen relative z-10">
      {/* Decorative ambient glowing orbs */}
      <div className="absolute top-[-10%] left-[-10%] w-[30rem] h-[30rem] rounded-full bg-seagreen-500/5 blur-[120px] pointer-events-none -z-10 animate-float-slow" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[35rem] h-[35rem] rounded-full bg-emerald-500/4 blur-[130px] pointer-events-none -z-10 animate-float-medium" />

      {/* Sleek full-width header navbar */}
      <header className="flex flex-col sm:flex-row items-center justify-between border-b border-slate-900/60 pb-6 mb-8 w-full gap-4">
        <div className="flex items-center gap-3">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-seagreen-500/20 bg-seagreen-500/5 text-seagreen-400 text-xs font-semibold tracking-wider uppercase">
            <Sliders className="w-3.5 h-3.5" />
            Client Sandbox
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-white">
            Pitch Changer
          </h1>
        </div>
        <p className="text-xs text-slate-500 max-w-xs text-center sm:text-right leading-normal">
          Change audio pitch live. Files never leave your browser context.
        </p>
      </header>

      {/* Content Area */}
      <div className="flex-grow w-full">
        {!file ? (
          /* Empty / Upload State layout */
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center py-6">
            {/* Left side: branding/intro */}
            <div className="lg:col-span-5 text-left flex flex-col gap-6 animate-fade-in pr-0 lg:pr-8">
              <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-white leading-tight">
                Adjust Your Pitch <br/>
                <span className="bg-clip-text text-transparent bg-gradient-to-r from-seagreen-400 to-emerald-300">
                  Instantly, Live.
                </span>
              </h2>
              <p className="text-sm sm:text-base text-slate-400 leading-relaxed">
                Change the pitch of any audio track directly in your browser. Our advanced pitch-shifting engine processes audio in real-time as it plays, without sending your data to any external server.
              </p>
              
              {/* Features list */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-2">
                <div className="p-4 rounded-xl border border-slate-900 bg-slate-950/20 backdrop-blur-md">
                  <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-1">Real-Time shifting</h3>
                  <p className="text-xs text-slate-500">Hear adjustments instantly using Web Audio API.</p>
                </div>
                <div className="p-4 rounded-xl border border-slate-900 bg-slate-950/20 backdrop-blur-md">
                  <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-1">Key Detection</h3>
                  <p className="text-xs text-slate-500">Visualizes resulting musical keys based on offset.</p>
                </div>
                <div className="p-4 rounded-xl border border-slate-900 bg-slate-950/20 backdrop-blur-md">
                  <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-1">High Quality Export</h3>
                  <p className="text-xs text-slate-500">Renders MP3 & WAV files using FFmpeg WASM.</p>
                </div>
                <div className="p-4 rounded-xl border border-slate-900 bg-slate-950/20 backdrop-blur-md">
                  <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-1">Local Processing</h3>
                  <p className="text-xs text-slate-500">Your files never leave your computer. 100% secure.</p>
                </div>
              </div>
            </div>
            
            {/* Right side: Uploader container */}
            <div className="lg:col-span-7 w-full animate-fade-in">
              <div className="w-full glass-card rounded-3xl p-8 shadow-2xl relative overflow-hidden transition-all duration-300 border border-slate-900">
                <AudioUploader
                  onFileSelect={handleFileSelect}
                  selectedFile={file}
                  duration={duration}
                  onReset={handleReset}
                />
              </div>
            </div>
          </div>
        ) : (
          /* Active State: Two-column Workspace layout */
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start py-4">
            
            {/* Left Column: File Info & Pitch Adjustment Controls */}
            <div className="lg:col-span-5 flex flex-col gap-6 w-full animate-fade-in">
              {/* Loaded file deck */}
              <div className="w-full">
                <AudioUploader
                  onFileSelect={handleFileSelect}
                  selectedFile={file}
                  duration={duration}
                  onReset={handleReset}
                />
              </div>

              {/* Pitch Shift Controls */}
              <div className="w-full">
                {!isProcessing && (
                  <PitchControls
                    value={pitchSemitones}
                    onChange={setPitchSemitones}
                    disabled={isProcessing}
                  />
                )}
              </div>
            </div>

            {/* Right Column: Audio Player, Processing Status, Export Console */}
            <div className="lg:col-span-7 flex flex-col gap-6 w-full animate-fade-in">
              {/* Playback module */}
              <div className="w-full">
                <AudioPlayer
                  controller={player}
                  title="Real-Time Audio Preview (adjust pitch slider on the left to shift)"
                  isActive={true}
                />
              </div>

              {/* Rendering status overlay */}
              <div className="w-full">
                <ProcessingStatus
                  progress={progress}
                  statusMessage={statusMessage}
                  isProcessing={isProcessing}
                />
              </div>

              {/* Actions & Export console */}
              {!isProcessing && (
                <div className="w-full glass-card rounded-2xl p-6 border border-slate-900/80 shadow-xl flex flex-col gap-4">
                  <div>
                    <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider text-left mb-1">
                      Render & Export Options
                    </h3>
                    <p className="text-xs text-slate-400 text-left leading-normal">
                      Render the adjusted pitch shifting into a standalone file. Renders are performed offline using WebAssembly.
                    </p>
                  </div>
                  
                  <div className="flex flex-col sm:flex-row gap-3 items-center justify-between border-t border-slate-900/60 pt-4 mt-2">
                    <div className="flex flex-col sm:flex-row gap-3 w-full sm:w-auto">
                      {/* Download MP3 */}
                      <button
                        onClick={() => exportAudio("mp3")}
                        disabled={isProcessing}
                        className="w-full sm:w-auto flex items-center justify-center gap-2 px-5 py-3 rounded-xl bg-seagreen-600 hover:bg-seagreen-500 text-white font-semibold text-sm transition-all hover:scale-[1.02] active:scale-100 shadow-md shadow-seagreen-500/10 disabled:opacity-50"
                      >
                        <Download className="w-4 h-4" />
                        Export MP3
                      </button>

                      {/* Download WAV */}
                      <button
                        onClick={() => exportAudio("wav")}
                        disabled={isProcessing}
                        className="w-full sm:w-auto flex items-center justify-center gap-2 px-5 py-3 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-slate-700 text-slate-200 font-semibold text-sm transition-all hover:scale-[1.02] active:scale-100 disabled:opacity-50"
                      >
                        <Download className="w-4 h-4" />
                        Export WAV
                      </button>
                    </div>

                    {/* Reset / Change File */}
                    <button
                      onClick={handleReset}
                      disabled={isProcessing}
                      className="w-full sm:w-auto flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-red-950/10 border border-red-950/20 hover:border-red-900/30 hover:bg-red-950/20 text-red-400 hover:text-red-300 text-xs font-semibold transition-colors disabled:opacity-50"
                    >
                      <Trash2 className="w-4 h-4" />
                      Clear File
                    </button>
                  </div>
                </div>
              )}

              {/* Error notifications */}
              {error && (
                <div className="w-full flex items-start gap-3 p-4 rounded-xl border border-red-900/30 bg-red-950/10 text-red-400 text-sm text-left animate-fade-in">
                  <AlertTriangle className="w-5 h-5 flex-shrink-0 text-red-500 mt-0.5" />
                  <div>
                    <h4 className="font-semibold mb-0.5">Export Failed</h4>
                    <p className="text-xs text-slate-400">{error}</p>
                  </div>
                </div>
              )}

            </div>
          </div>
        )}
      </div>

      {/* Security sandbox footer */}
      <div className="flex items-center gap-2 mt-12 text-xs text-slate-600 justify-center">
        <ShieldCheck className="w-4 h-4 text-emerald-500/50" />
        <span>100% Secure Client Sandbox: Files never leave your browser context.</span>
      </div>
    </main>
  );
}
